name: Azure Template Tests
on:
  push:
    branches:
      - main
jobs:
  test_templates:
    runs-on: ubuntu-latest
    env:
      ttk.folder: ./file
      ttk.uri: https://raw.githubusercontent.com/kar122/aksmanagedapp/main/app.zip
      ttk.asset.filename: app.zip
      sample.folder: ./mainTemplate.json
    steps:
      - name: Download TTK
        run: |
          New-Item '$(ttk.folder)' -ItemType Directory
          Invoke-WebRequest -uri '$(ttk.uri)' -OutFile "$(ttk.folder)/$(ttk.asset.filename)" -Verbose
          Get-ChildItem '$(ttk.folder)' -Recurse
          Write-Host "Expanding files..."
          Expand-Archive -Path '$(ttk.folder)/*.zip' -DestinationPath '$(ttk.folder)' -Verbose
          Write-Host "Expanded files found:"
          Get-ChildItem '$(ttk.folder)' -Recurse
        displayName: Download TTK
      - name: Run Best Practices Tests
        run: |
          Import-Module $(ttk.folder)/arm-ttk/arm-ttk.psd1 -Verbose
          $testOutput = @(Test-AzTemplate -TemplatePath "$(sample.folder)")
          $testOutput
          if ($testOutput | ? {$_.Errors }) {
            exit 1 
          } else {
            Write-Host "##vso[task.setvariable variable=result.best.practice]$true"
            exit 0
          } 
        errorActionPreference: continue
        failOnStderr: true
        displayName: Run Best Practices Tests
        continueOnError: true
