name: Clone Repo

on:
  push:
    branches:
      - main

jobs:
  clone_repo:
    runs-on: windows-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          repository: Azure/arm-ttk
          ref: armttk
          path: kar122/clonerepo/armttk
