name: ARM-TTK Validation

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: windows-latest
    steps:
      - name: Install Azure PowerShell Module
        uses: Azure/powershell@v1
        with:
          azPSVersion: '3.1.0'
          inlineScript: |
            #Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
            #choco Install azure-cli -y
      - name: Clone ARM-TTK 
        timeout-minutes: 5
        run: |
          mkdir karthik
          cd .\karthik
          git clone https://github.com/Azure/arm-ttk.git
      - name: Upload mainTemplate.json
        uses: actions/upload-artifact@v2
        with:
          name: mainTemplate
          path: ./karthik/arm-ttk/mainTemplate.json
      - name: Validate ARM templates using ARM-TTK
        shell: pwsh
        run: |
          cd .\karthik
          dir
          cd .\arm-ttk
          dir
          Invoke-WebRequest -Uri "https://github.com/kar122/clonerepo/blob/main/mainTemplate.json" -UseBasicParsing -OutFile "mainTemplate.json"
          dir
          Test-AzTemplate -Path "mainTemplate.json"
      - name: Download mainTemplate.json
        uses: actions/download-artifact@v2
        with:
          name: mainTemplate
          path: ./karthik/arm-ttk
